In [1]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.6815, 0.6148, 0.8938],
        [0.5906, 0.3269, 0.7067],
        [0.3725, 0.7860, 0.5225],
        [0.5307, 0.5724, 0.0833],
        [0.0214, 0.3139, 0.2827]])


In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)  

tensor([[-0.5927,  0.3067,  0.2081],
        [-1.2723, -0.0430,  1.9101],
        [ 0.1686, -1.4935, -0.5816],
        [ 0.9733,  0.3551, -0.8533],
        [-0.2232, -0.5984,  1.6108]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.5327,  0.8641,  1.0695],
        [-0.4513,  0.3218,  2.0708],
        [ 0.7342, -1.3381, -0.1488],
        [ 1.1869,  1.2028, -0.8094],
        [ 0.0186, -0.5614,  1.6722]])


In [9]:
print(torch.add(x, y))

tensor([[-0.5327,  0.8641,  1.0695],
        [-0.4513,  0.3218,  2.0708],
        [ 0.7342, -1.3381, -0.1488],
        [ 1.1869,  1.2028, -0.8094],
        [ 0.0186, -0.5614,  1.6722]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.5327,  0.8641,  1.0695],
        [-0.4513,  0.3218,  2.0708],
        [ 0.7342, -1.3381, -0.1488],
        [ 1.1869,  1.2028, -0.8094],
        [ 0.0186, -0.5614,  1.6722]])


In [11]:
# adds x to y, in-place
y.add_(x)
print(y)

tensor([[-0.5327,  0.8641,  1.0695],
        [-0.4513,  0.3218,  2.0708],
        [ 0.7342, -1.3381, -0.1488],
        [ 1.1869,  1.2028, -0.8094],
        [ 0.0186, -0.5614,  1.6722]])


In [12]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[:, 1])

tensor([ 0.3067, -0.0430, -1.4935,  0.3551, -0.5984])


In [13]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x

tensor([[-0.3901,  0.9459, -1.3446, -0.3841],
        [ 1.2183,  1.4657, -1.0912,  0.6834],
        [-0.1181, -1.1988, -0.0707,  1.1649],
        [ 0.0921,  0.2077,  0.5747,  0.1909]])

In [17]:
y

tensor([-0.3901,  0.9459, -1.3446, -0.3841,  1.2183,  1.4657, -1.0912,  0.6834,
        -0.1181, -1.1988, -0.0707,  1.1649,  0.0921,  0.2077,  0.5747,  0.1909])

In [19]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5761])
0.5761394500732422


In [20]:
# 100 useful tensor operations: https://pytorch.org/docs/stable/torch.html

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

#### Converting a Torch Tensor to a NumPy Array

In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [24]:
# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
